### ISSUE TITLE
How to put initial value on page load?

### ISSUE THREAD

**Issue by ariesbrylle-bms** [aJIEw/react-native-tag-group#2]

**Comment by aJIEw** [comment]
you can put them in the state and initialize them in the constructor

**Comment by ariesbrylle-bms** [comment]
Can I see your sample code for it? There's no sample in the readme file. Thank you.

**Comment by aJIEw** [comment]
go check the [example](https://github.com/aJIEw/react-native-tag-group/blob/master/example/App.js) folder, I don't think you read all the readme and missed the last sentence but we all do that ¯\_(ツ)_/¯

**Comment by ariesbrylle-bms** [comment]
TypeError: statRef.select is not a function. (In 'statRef.select(0)', 'statRef.select' is undefined)

![image](https://user-images.githubusercontent.com/22163768/102704612-a388cf80-42b8-11eb-9cfa-5e904b11a975.png)

`
useEffect(() => {
		if (isVisible) {
			console.log(statRef.select(0));
		}
	}, [isVisible]);

<TagGroup
							ref={statRef}
							source={[
								"All",
								"Created",
								"Processing",
								"Reassigned",
								"Resolved",
							]}
							onSelectedTagChange={(selected) => {
								//console.log(statRef);
								setSearchStatus(selected);
							}}
							singleChoiceMode={true}
							tagStyle={{
								height: 35,
								borderWidth: 1,
								borderColor: CONSTANTS.TEXT_COLOR,
							}}
							textStyle={{
								alignItems: "center",
								alignContent: "center",
								padding: 4,
							}}
							activeTagStyle={{
								borderColor: CONSTANTS.PRIMARY_COLOR,
								backgroundColor: CONSTANTS.PRIMARY_COLOR,
							}}
							activeTextStyle={{ color: "white" }}
						/>`

**Comment by aJIEw** [comment]
if you want to create refs of a component do it like this `ref={component => this.refName = component}`, I'd recommend you to read the [react doc](https://reactjs.org/docs/refs-and-the-dom.html)

**Comment by ariesbrylle-bms** [comment]
Thank you for your help. For future reference, here's how I solved it.

![image](https://user-images.githubusercontent.com/22163768/102714342-dd81c200-4308-11eb-81ab-6b8021f7bd6b.png)
